### ISSUE TITLE
AttributeError: 'list' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by adrianreber** [fedora-infra/mirrormanager2#178]
In staging:

Traceback (most recent call last):
  File "/usr/share/mirrormanager2/mirrorlist_client.wsgi", line 156, in application
    results = keep_only_http_results(results)
  File "/usr/share/mirrormanager2/mirrorlist_client.wsgi", line 129, in keep_only_http_results
    if url.startswith(u'http'):
AttributeError: 'list' object has no attribute 'startswith'

This request triggers the error: https://mirrors.stg.fedoraproject.org/mirrorlist?path=pub/fedora/linux/&redirect=1

Everything using redirect=1 is broken since 0.7.2 has been installed in staging.

**Comment by adrianreber** [comment]
Fixed version deployed.
