### ISSUE TITLE
Instructions to try out mm2 don't work anymore

### ISSUE THREAD

**Issue by keestux** [fedora-infra/mirrormanager2#321]
Both "Hacking with Vagrant" and "Manual Setup" don't work out of the box.

The vagrant method wants to install freeipa-client, but there is no documentation at all how that should work if you don't have a FreeIPA invironment `tinystage.test`.

The manual method fails on Fedora 38. After setting up a virtualenv and pip install I get:
```
$ python createdb.py
Traceback (most recent call last):
  File "/home/keesb/src/mirrormanager2/createdb.py", line 7, in <module>
    from mirrormanager2.app import APP
  File "/home/keesb/src/mirrormanager2/mirrormanager2/app.py", line 101, in <module>
    import mirrormanager2.lib as mmlib
  File "/home/keesb/src/mirrormanager2/mirrormanager2/lib/__init__.py", line 37, in <module>
    from mirrormanager2.lib import model
  File "/home/keesb/src/mirrormanager2/mirrormanager2/lib/model.py", line 39, in <module>
    from sqlalchemy.orm import relation
ImportError: cannot import name 'relation' from 'sqlalchemy.orm' (/home/keesb/src/mirrormanager2/venv/lib64/python3.11/site-packages/sqlalchemy/orm/__init__.py)
```

**Comment by keestux** [comment]
@abompard You've removed `requirements.txt`, but you haven't updated `README.rst` where it is still used in the description https://github.com/fedora-infra/mirrormanager2#manual-setup

**Comment by keestux** [comment]
Still an error. During `vagrant up`
```
TASK [dev : Install python packages from requirements.txt] *********************
fatal: [mirrormanager2]: FAILED! => {"changed": false, "cmd": ["/usr/bin/python3", "-m", "pip.__main__", "install", "-r", "/vagrant/requirements.txt"], "msg": "\n:stderr: ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/vagrant/requirements.txt'\n"}
```

**Comment by abompard** [comment]
Alright, the latest commit in HEAD should fix the Vagrant env. Sorry about that.
