### ISSUE TITLE
handle unreadable pre-release versions in umdl

### ISSUE THREAD

**Issue by nirik** [fedora-infra/mirrormanager2#407]
We had this at beta and I worked around it, but the downstream issue was closed and we never followed up. ;( 

So, now we are back in the same situation.

The primary-mirror-fedora umdl is failing because we have f41 content in fullfiletimelist, but that content is not open until the actual release day (tuesday). 

```
Hmm, stat()ing /srv/pub/fedora/linux/releases/41/Onyx/x86_64/os failed. Theoretically this cannot happen. [Errno 13] Permission denied: '/srv/pub/fedora/linux/releases/41/Onyx/x86_64/os'
Hmm, stat()ing /srv/pub/fedora/linux/releases/41/Onyx/x86_64 failed. Theoretically this cannot happen. [Errno 13] Permission denied: '/srv/pub/fedora/linux/releases/41/Onyx/x86_64'
Hmm, stat()ing /srv/pub/fedora/linux/releases/41/Onyx failed. Theoretically this cannot happen. [Errno 13] Permission denied: '/srv/pub/fedora/linux/releases/41/Onyx'
Syncing directories of Fedora Linux ━━━━━━━━━━━━━━━━━━━                       49% 0:00:26
Traceback (most recent call last):
  File "/opt/app-root/bin/mm2_update-master-directory-list", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/app-root/lib64/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.11/site-packages/mirrormanager2/utility/update_master_directory_list.py", line 760, in main
    check_category(
  File "/opt/app-root/lib64/python3.11/site-packages/mirrormanager2/utility/update_master_directory_list.py", line 810, in check_category
    syncer.sync(**extra_args)
  File "/opt/app-root/lib64/python3.11/site-packages/mirrormanager2/utility/update_master_directory_list.py", line 132, in sync
    self.sync_directories(category_directories)
  File "/opt/app-root/lib64/python3.11/site-packages/mirrormanager2/utility/update_master_directory_list.py", line 217, in sync_directories
    loader.load()
  File "/opt/app-root/lib64/python3.11/site-packages/mirrormanager2/lib/umdl.py", line 204, in load
    md5dict = self._checksums_from_globs(self.md5_globs, 32)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.11/site-packages/mirrormanager2/lib/umdl.py", line 169, in _checksums_from_globs
    for f in self._get_filenames():
  File "/opt/app-root/lib64/python3.11/site-packages/mirrormanager2/lib/umdl.py", line 177, in _get_filenames
    yield from os.listdir(os.path.join(self.config["UMDL_PREFIX"], self.relative_dir_name))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/srv/pub/fedora/linux/releases/41'
umdl for Fedora Linux returned non-zero. Something failed.Sat Oct 26 04:19:03 PM UTC 2024
```

I think we actually don't want it to read this content, because we are still sending users to development/41/ until a week or two after release. So, perhaps it could just gracefull catch that and go on so it can update all the rest?

**Comment by nirik** [comment]
Alternately, if it's ok to update these trees, we could figure a way to let the umld update pod read that content, perhaps giving it a secondary group of  groups=263(ftpsync)?

**Comment by nirik** [comment]
Thinking about it more, it didn't break beta users, so hopefully it will work ok here. 
I am pushing a change to add a supplementary group of 263 to allow it to hopefully read pre bitflip content.

**Comment by nirik** [comment]
ok. Added that finally (with a few false turns). It updated... so we will see how it goes. ;)

**Comment by nirik** [comment]
ok. It updated, so far so good.

**Comment by adrianreber** [comment]
Just for context, MirrorManager always had access to the pre-release bits. I think it is not a problem as we are using the content from `development/<version>` during the first few days anyway. So even if MirrorManager detects something earlier it is not giving that to users.

I also think fullfiletimelist marks pre-release bits with a `-`.
