### ISSUE TITLE
Handle OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by adrianreber** [fedora-infra/mirrormanager2#73]
If situation where not much memory is available the crawler cannot spawn rsync processes to crawl a certain mirror. Currently this fails like this:

```
WARNING - Failed to run rsync.
Traceback (most recent call last):
  File "/usr/bin/mm2_crawler", line 704, in try_per_category
    result, listing = run_rsync(url, params, logger)
  File "/usr/lib/python2.7/site-packages/mirrormanager2/lib/sync.py", line 46, in run_rsync
    bufsize=-1
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1205, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

This is not handled at all and needs proper handling, logging and reporting.

**Comment by pypingou** [comment]
So looking at:
- https://github.com/fedora-infra/mirrormanager2/blob/master/utility/mm2_update-master-directory-list#L536
- https://github.com/fedora-infra/mirrormanager2/blob/master/utility/mm2_update-master-directory-list#L536
- the output of ``git grep run_rsync``

I think we can close this issue
